Update state-contact.js
COVID19Tracking/website pull request #1626
Opened 2020-11-22 16:40 UTC by theroyalpekka

This Pull request is in response to the Issue #1608 , adding 
 {
  padding-left: 4px;
}
fulfills the requiring gap.

2020-11-23 15:04 UTC, kevee requested changes
Hi, @theroyalpekka, let's not use CSS to do this and instead just insert a `{' '}` to create an actual space instead.

2020-11-23 15:04 UTC, kevee commented
Also, please update the test snapshots by running `yarn test:update`

2020-11-24 15:47 UTC, ivarvong commented
Resolved here: https://github.com/COVID19Tracking/website/pull/1633

2020-11-24 16:07 UTC, kevee commented
Closing, this issue was resolved in #1633

2020-11-24 16:07 UTC, closed without merging